### Importing Libraries

In [76]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Importing the dataset

In [77]:
dataset = pd.read_csv("Data.csv")
dataset.head(n=10)
# X is out matrix of features & y is the dependent variable
X = dataset.iloc[:, :-1].values # Locate indices of first 3 columns
y = dataset.iloc[:, -1].values # Locate index of the last column
print(X), print(y) #.values allows us to store X & y as np arrays

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


(None, None)

### Handling Missing Data/NaN Values

In [78]:
# Several ways of handling missing data:
# 1) Remove all occurrences - valuable if the missing data is small in proportion to the whole dataset
# 2) Replace occurrences by the (mean, median, mode) of present data

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# we replace all occurrences of NaN with the mean
imputer.fit(X[:, 1:3]) 
# the argument of imputer.fit must be numeric columns of
# desired sub-dataset
# .fit will identify NaN values & compute means 
# .transform will perform the data swapping
X[:, 1:3] = imputer.transform(X[:, 1:3]) # swapping of data takes place
print(X)



[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### Transforming Categorical Variables - Matrix of Features

In [79]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [80]:
# Applying OneHot Encoding to our Dependent Variable

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


### Forming the training and testing set

In [81]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [82]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [83]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [84]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [85]:
print(y_test)

[0 1]


### Feature Scaling

In [86]:
# Feature Scaling should be performed AFTER obtaining
# the training and testing sets in order to avoid
# INFORMATION LEAKAGE

# Feature scaling allows us to put all features on a similar
# scale to avoid some features dominating others unnecessarily

# Main techniques of feature scaling:
# 1) Standardization: (x - mean(x))/std.dev(x)
# 2) Normalization: (x - min(x))/(max(x)-min(x))

# Standardization works well in general
# Normalization recommended when features are normally distriibuted

# Feature scaling will only be applied to X_train

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:]) # Use the SAME scaler
# We do not have to apply feature scaling to encoded variables

print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [87]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
